### PR TITLE
Mf/blackhole host detector

### PR DESCRIPTION
**Pull request by mforsyth**
@dgrnbrg  This is my first stab at https://github.com/twosigma/satellite/issues/40.

I've tested it using artificial event totals and it kicks in when it's supposed to.

I can definitely see the utility that integration testing would bring here... so I am excited to work on that next.  It would be nice to have automated tests which ensure that satellite-slave and satellite-master behave correctly together.

### CODE REVIEW

**Comment by mforsyth** [comment]
Thanks for the review @wkf .  I will adjust & resubmit this tomorrow.

**Comment by mforsyth** [comment]
@wkf Ready for another look.

**Comment by wkf** [comment]
Thanks @mforsyth, just 1 small comment this time.

**Comment by mforsyth** [comment]
@wkf ready once more.

**Pull request merged**
