### PR TITLE
Slave advertise 

### PR DESCRIPTION
**Pull request by ch3lo**
This "PR" override the auto generated Slave Hostname.

You can assign the slave hostname with advertise parameter.

Signed-off-by: Marcelo Salazar <chelosalazar@gmail.com>

### CODE REVIEW

**Comment by mforsyth** [comment]
Hi @ch3lo, thanks for making this pull request!  

You are assuming that the hostname that will be used to tag events is the same hostname that you want to use when connecting to the Mesos monitoring API.   Although it wouldn't necessarily always be true, this would usually be a reasonable assumption (and it's definitely better than just hardcoding both to be lookups of the hostname of the local host) so :+1: .

However, let's still call the function "get-slave-host" (moving it to util as you have done is fine), and let's call the setting "slave-host".  This value influences more than just "advertising" - it's also the identifier by which the mesos slave is reached.  In both purposes "slave-host" describes the purpose of the value we're talking about.

Thanks again @ch3lo

**Comment by ch3lo** [comment]
Hi @mforsyth ,

I made the suggested changes. Is a pleasure collaborate with your project.

Regards

**Comment by ch3lo** [comment]
I rebase my branch with the last commit.

I think all should be ok.

**Comment by mforsyth** [comment]
@c3hlo would you mind squashing these 2 commits down into 1?  It will be better for the history since the second commit is just an adjustment of the first commit.   After that we should be good to go!  Thanks!

**Comment by ch3lo** [comment]
ready

**Comment by mforsyth** [comment]
Thanks again.  I hate to be a pain @ch3lo but I just realized that in order for this to be merged you have to sign Two Sigma's CLA - it's mentioned in the Readme.  Can you fill out that form & send it in as per instructions?

**Comment by ch3lo** [comment]
Sent

**Comment by mforsyth** [comment]
Thanks @ch3lo !

**Pull request merged**
