### PR TITLE
Introduce ansible deploy script.

### PR DESCRIPTION
**Pull request by mforsyth**
Using these playbooks, I was able to successfully deploy Satellite to my Debian cluster.

I started based on https://github.com/twosigma/satellite/pull/16 and modified from there.

I do have some questions.  I think the clearest way for me to ask is to comment on the code in my own pull request - which I'll be doing over the next half hour or so.

### CODE REVIEW

**Comment by mforsyth** [comment]
One could divide the tasks in this playbook into two categories:
-Deploy Satellite
-Configure Satellite.

"Deploy Satellite" involves just copying the jar and very simple init script to configurable locations on the servers.  In the long term, this probably be better done using actual packages - e.g. a .deb that installs Satellite on debian/ubuntu servers.   That way, we could use the more sophisticated dependency management and init systems that come with linux distributions and other OS's.  So I'm thinking of this deployment functionality as a bit of a stopgap.

"Configure Satellite" - I imagine that many Satellite are reconfiguring relatively frequently - testing out new Riemann handlers, etc.  And needing to reconfigure all servers in a cluster at once is probably always going to be a pretty common task, so this category of tasks seems like it will have relevance no matter how the initial install/deploy processes change.  

For now I've left the deploy & configure tasks together as a part of the same playbook - but if you prefer, I can separate them into two playbooks for both the masters and slaves.

**Comment by mforsyth** [comment]
The original pull request contained some unfinished code that was attempting to identify the Master leader... I didn't see why this was necessary (the other Ansible scripts didn't use it), so I took it out.  Was this the right thing to do?

**Comment by dgrnbrg** [comment]
Couldn't satellite-recipes just be in the same directory as the JVM was started in?

**Comment by mforsyth** [comment]
@dgrnbrg generally the current directory "." isn't actually on the PATH.

**Comment by mforsyth** [comment]
Hmm, I could make it so the init script adds "." to PATH prior to launching java though...   if you prefer I can do that @dgrnbrg  and keep all files in the satellite_deploy_dir.

**Comment by dgrnbrg** [comment]
I'm pretty sure that the deploy scripts shouldn't need sudo, but there are
many acceptable solutions to that.

**Comment by mforsyth** [comment]
@dgrnbrg OK, I will change it.  Actually I think the perfect thing is another wrinkle:  change the init script to put the actual {{ satellite_install_dir }} in the path - that way the init script is more, and could be launched from any working directory and still find satellite_recipes, and we wouldn't need sudo anywhere.

**Comment by mforsyth** [comment]
@dgrnbrg OK, i've changed it to avoid sudo and keep everything in a single "install directory".  Thanks for the feedback, this is much better.

**Comment by mforsyth** [comment]
@dgrnbrg @sabraham @leifwalsh Any more thoughts?  Are we looking good here?

**Comment by sabraham** [comment]
Need Apache header on all new files, else looks good!

**Comment by mforsyth** [comment]
@sabraham roger that...

**Comment by sabraham** [comment]
looks good :+1:

**Comment by dgrnbrg** [comment]
I feel like we should be shipping satellite installation with a supervision tool; whether SystemD, supervisor, or monit.

Also, is there a way to build an "ansible package"? So that it's easy to use/import this config without cloning it and copying it into position?

**Comment by mforsyth** [comment]
@dgrnbrg Re: supervision tool.  Won't many users already be tied to a specific supervision tool?  Do you think it is a good idea to couple Satellite to a specific choice?

**Comment by mforsyth** [comment]
About "ansible packages".... I see this (or any) ansible script as being a "starting point" that people can incorporate into their own environment-specific set of ansible playbooks, not "plug as-is into your production infrastructure".   I don't see how we can avoid the user having to configure the behavior of satellite & other settings like where to put the satellite config files & the jar.  So it seems like the best we can do via Ansible is to provide some playbooks which will be useful for many of the types of environments we would want to support, and require the user to fill in the parts we don't know about the specific machines to which they want to deploy and/or reconfigure Satellite.

**Comment by mforsyth** [comment]
I added a couple of github issues earlier about creating distribution-specific packages - if we want to provide a robust installation process, it should involve those, not just an ansible script.   

Also, see my first comment on this PR - you can usefully divide the tasks performed by these scripts into "deploying Satellite" and "Reconfiguring satellite"... ansible scripts to perform the latter could be useful no matter how Satellite gets installed.

**Comment by dgrnbrg** [comment]
I agree that this should be a starting point, but even a basic installation should give satellite supervision--it doesn't make sense to ship w/ deployment scripts that couldn't be used for a stable deployment.

I think that picking a supervision system to launch with is a fine compromise--users can change that as they see fit, but at least if they don't change anything, the deployment itself will be fine.

**Comment by mforsyth** [comment]
OK @dgrnbrg :+1:  I will look into the possibility of including a supervision solution...  I will post back here with further questions and/or comments.

**Comment by dgrnbrg** [comment]
I strongly suggest supervisord--we've been using it for years, and it's extremely lightweight.

**Comment by mforsyth** [comment]
@dgrnbrg thanks for the direction, let's see what integrating that into the playbooks will look like :+1: .

**Comment by mforsyth** [comment]
For any given supervision solution (including supervisord) there are already multiple open source projects whose purpose is to install that the solution via Ansible...  any reason (licensing, etc) not to use one of those, e.g. https://github.com/zenoamaro/ansible-supervisord, and then configure it to watch Satellite afterwards?

**Comment by mforsyth** [comment]
We could formally depend on one of these projects via Ansible itself using ansible-galaxy:  https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=supervisor

**Comment by mforsyth** [comment]
Actually, Satellite itself could be a Role in Ansible Galaxy, for playbook authors to depend on formally rather than taking pieces out of this repo manually.  Is this what you meant earlier by "Ansible Package" @dgrnbrg ?

**Comment by dgrnbrg** [comment]
Yes, I was thinking of satellite being in ansible galaxy. I'm not sure what goes into that, though.

**Comment by mforsyth** [comment]
@dgrnbrg OK.  After having done some more research, 2 things to note about this PR:

1.  I do think that I should move most of the business here into a Role, and provide a minimal sample playbook that uses the Role.  In addition to making it easier to incorporate Satellite into existing sets of playbooks, that will pave the way to exposing Satellite on Ansible Galaxy.

2.  It seems more useful to make the Satellite Role depend on systemd for monitoring rather than supervisord.  Systemd is already the default init system of Debian, Redhat, Arch, and soon Ubuntu, so it's barely an "opinion" to include monitoring via systemd.  

Is it OK if I just include a systemd unit file rather than a dependency on a Role which installs supervisord?

If desired I can also include an example of how to use it with supervisord...

**Comment by dgrnbrg** [comment]
I think that having both would be good. Particularly, in environments like TS's, it's not possible to run software as root. Since the SystemD installation would require root to install the unit file (unless it doesn't), we should have a non-root alternative. Of course, using the default init system is better for most other users.

**Comment by mforsyth** [comment]
:+1: @dgrnbrg It makes sense for the out-of-the-box Role to use systemd (and we can't assume that users will have configured systemd to allow non-root access to systemd), but I will also include a specific example of how to set it up with supervisord (even a suggested role from Galaxy which will install supervisord, although anyone who needs to use a different supervision solution probably already has their specific solution installed).

**Comment by dgrnbrg** [comment]
SGTM

**Pull request closed without merging**
